# Sesión 2: Ejercicios planteados

Este notebook contiene los ejercicios planteados para la Sesión 2 de la librería *pandas*. En este ejercicio, vas a estar trabajando con una base de datos que contiene información de empleados de una empresa. Descarga el fichero `empleados.csv` que vas a tener que usar.

En los trabajos como analistas o científicos de datos, es importante acostumbrarse a trabajar con juegos de datos diferentes y entenderlos. Para ello, en ocasiones tendréis que revisar el libro de códigos (*codebook*), donde se suele describir el racional de cada una de las variables de un juego de datos. El fichero `empleados.csv` contiene las siguientes variables:


* **Nombre**: Nombre de pila del empleado.
* **Genero**: Genero del empleado (Hombre/Mujer)
* **FechaComienzo**: Fecha del primer día de trabajo.
* **UltimoLogin**: Hora de la última vez que salió de la empresa.
* **Salario**: Salario en dólares.
* **Bonus %**: Porcentaje de bonus en el último año.
* **Manager**: Variable binaria que indica si es manager o no.
* **Equipo**: Departamento de la empresa al que está afiliado.

---

## *Ejercicio2-1 ❗

**Parte 1**: Carga el fichero `empleados.csv` con la librería `read_csv()` de pandas y muestralo por pantalla. Verifica que se está mostrando todo bien. ¿Cuántas filas y columnas tiene?

**Parte 2**: Por necesidades de software, desearías exportar el juego de datos también como CSV, pero usando un punto y coma (`;`) para separar los campos. Utiliza el `to_csv()` para exportar el `DataFrame`, usando punto y coma como separador, y sin añadir índice ni cabecera, con el nombre de fichero `nuevo_empleados.csv`. Verifica el fichero generado en el visor de Google Colab.

In [14]:
import pandas as pd

empleados = pd.read_csv("empleados.csv")

df_csv = empleados.to_csv("nuevo_empleados.csv", sep=";", index=False, header=False)

---

## *Ejercicio2-2 ❗

**Parte 1**: Como se vio en la sesión anterior, los objetos DataFrame tienen un índice para identificar cada fila. Te gustaría tener un índice que identificara a cada fila, cada empleado, de forma unívoca, es decir, que cada fila tuviese un índice propio y único. Verifica si es posible usar el nombre como índice inequívoco. 

Si la respuesta es que no, concatena dos columnas que potencialmente puedan identificar inequívocamente un empleado y establécelo como índice. Para establecer un índice se emplea el método `set_index` en el Dataframe; la concatenación de columnas se puede realizar con el signo + dentro de la operación de `set_index`.

**Parte 2**: En este caso, no vas darle uso a la variable UltimoLogin, así que elimínala del objeto DataFrame.

In [15]:
len(empleados["Nombre"].unique())

empleados.set_index(empleados["Nombre"]+"_"+empleados["FechaComienzo"], inplace=True)

In [16]:
print(empleados)

                    Nombre  Genero FechaComienzo UltimoLogin  Salario  \
Douglas_8/6/1993   Douglas   Mujer      8/6/1993    12:42 PM    97308
Thomas_3/31/1996    Thomas  Hombre     3/31/1996     6:53 AM    61933
Maria_4/23/1993      Maria   Mujer     4/23/1993    11:17 AM   130590
Jerry_3/4/2005       Jerry  Hombre      3/4/2005     1:00 PM   138705
Larry_1/24/1998      Larry  Hombre     1/24/1998     4:47 PM   101004
...                    ...     ...           ...         ...      ...
Henry_11/23/2014     Henry     NaN    11/23/2014     6:09 AM   132483
Phillip_1/31/1984  Phillip  Hombre     1/31/1984     6:30 AM    42392
Russell_5/20/2013  Russell  Hombre     5/20/2013    12:39 PM    96914
Larry_4/20/2013      Larry  Hombre     4/20/2013     4:45 PM    60500
Albert_5/15/2012    Albert  Hombre     5/15/2012     6:24 PM   129949

                   Bonus % Manager                 Equipo
Douglas_8/6/1993     6.945    True              Marketing
Thomas_3/31/1996     4.170    True                    NaN
Maria_4/23/1993     11.858   False               Finanzas
Jerry_3/4/2005       9.340    True               Finanzas
Larry_1/24/1998      1.389    True    Servicio al Cliente
...                    ...     ...                    ...
Henry_11/23/2014    16.655   False           Distribución
Phillip_1/31/1984   19.675   False               Finanzas
Russell_5/20/2013    1.421   False               Producto
Larry_4/20/2013     11.985   False  Desarrollo de Negocio
Albert_5/15/2012    10.169    True                 Ventas

[1000 rows x 8 columns]

In [17]:
del empleados["UltimoLogin"]
print(empleados)

                    Nombre  Genero FechaComienzo  Salario  Bonus % Manager  \
Douglas_8/6/1993   Douglas   Mujer      8/6/1993    97308    6.945    True
Thomas_3/31/1996    Thomas  Hombre     3/31/1996    61933    4.170    True
Maria_4/23/1993      Maria   Mujer     4/23/1993   130590   11.858   False
Jerry_3/4/2005       Jerry  Hombre      3/4/2005   138705    9.340    True
Larry_1/24/1998      Larry  Hombre     1/24/1998   101004    1.389    True
...                    ...     ...           ...      ...      ...     ...
Henry_11/23/2014     Henry     NaN    11/23/2014   132483   16.655   False
Phillip_1/31/1984  Phillip  Hombre     1/31/1984    42392   19.675   False
Russell_5/20/2013  Russell  Hombre     5/20/2013    96914    1.421   False
Larry_4/20/2013      Larry  Hombre     4/20/2013    60500   11.985   False
Albert_5/15/2012    Albert  Hombre     5/15/2012   129949   10.169    True

                                  Equipo
Douglas_8/6/1993               Marketing
Thomas_3/31/1996                     NaN
Maria_4/23/1993                 Finanzas
Jerry_3/4/2005                  Finanzas
Larry_1/24/1998      Servicio al Cliente
...                                  ...
Henry_11/23/2014            Distribución
Phillip_1/31/1984               Finanzas
Russell_5/20/2013               Producto
Larry_4/20/2013    Desarrollo de Negocio
Albert_5/15/2012                  Ventas

[1000 rows x 7 columns]

---

## *Ejercicio2-3 ❗

Crea un nuevo dataframe filtrado, que contenga aquellos empleados que tengan un `salario > 120000`, y que sean `Hombre` o `Manager`. Guárdalo en un nuevo objeto DataFrame que se llame `mejor_pagados`. ¿Cuántos casos hay? Selecciona con una sola sentencia los tres empleados de entre los mejor pagados (del DataFrame mejor_pagados) que tienen los índices enteros 55, 56 y 57.

In [18]:
mp = empleados[(empleados['Salario'] > 120000) & ((empleados['Genero'] == "Hombre") | (empleados["Manager"] == True))] 
mp
mp[55:58]

,Nombre,Genero,FechaComienzo,Salario,Bonus %,Manager,Equipo
Gregory_7/9/2011,Gregory,NaN,7/9/2011,137661,4.805,True,Ventas
Robert_10/29/1994,Robert,Hombre,10/29/1994,123294,19.894,False,Servicio al Cliente
Gloria_9/19/1989,Gloria,Mujer,9/19/1989,131045,11.312,True,Producto

---

## *Ejercicio2-4 ❗

Dentro de los `mejor_pagados`, ¿quiénes son los cinco que han recibido el menor `Bonus %`? Solucionalo con una sola sentencia.

In [20]:
(mp.sort_values(["Bonus %"], ascending=True)).head(5)

,Nombre,Genero,FechaComienzo,Salario,Bonus %,Manager,Equipo
Willie_12/5/2009,Willie,Hombre,12/5/2009,141932,1.017,True,Ingeniería
Joe_12/8/1998,Joe,Hombre,12/8/1998,126120,1.020,False,NaN
Willie_2/17/1998,Willie,Hombre,2/17/1998,146651,1.451,True,Ingeniería
Margaret_1/4/2001,Margaret,Mujer,1/4/2001,126924,1.552,True,Finanzas
Joe_12/5/2010,Joe,Hombre,12/5/2010,144082,1.620,True,Servicio al Cliente

---

## *Ejercicio2-5 ❗

¿Tiene el juego de datos valores faltantes? ¿Cuántos en cada columna? Has decidido que, aquellos empleados que no tengan `Nombre`, deben ser eliminados, y aquellos que no tengan `Equipo`, se les debe introducir el valor `"Desconocido"`.

In [ ]:
empleados.isna().sum()
empleados.dropna(subset="Nombre", inplace=True)
empleados["Equipo"].fillna("Desconocido", inplace=True)
empleados

C:\Users\adrcu\AppData\Local\Temp\ipykernel_6120\1064546394.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  empleados["Equipo"].fillna("Desconocido", inplace=True)

,Nombre,Genero,FechaComienzo,Salario,Bonus %,Manager,Equipo
Douglas_8/6/1993,Douglas,Mujer,8/6/1993,97308,6.945,True,Marketing
Thomas_3/31/1996,Thomas,Hombre,3/31/1996,61933,4.170,True,Desconocido
Maria_4/23/1993,Maria,Mujer,4/23/1993,130590,11.858,False,Finanzas
Jerry_3/4/2005,Jerry,Hombre,3/4/2005,138705,9.340,True,Finanzas
Larry_1/24/1998,Larry,Hombre,1/24/1998,101004,1.389,True,Servicio al Cliente
...,...,...,...,...,...,...,...
Henry_11/23/2014,Henry,NaN,11/23/2014,132483,16.655,False,Distribución
Phillip_1/31/1984,Phillip,Hombre,1/31/1984,42392,19.675,False,Finanzas
Russell_5/20/2013,Russell,Hombre,5/20/2013,96914,1.421,False,Producto
Larry_4/20/2013,Larry,Hombre,4/20/2013,60500,11.985,False,Desarrollo de Negocio
Albert_5/15/2012,Albert,Hombre,5/15/2012,129949,10.169,True,Ventas

---

## *Ejercicio2-6 ❗

Analiza si observas diferencias en la media y la mediana del salario obtenidos entre los dos géneros, una vez que separamos por departamento. Resuélvelo en una sola sentencia.

In [22]:
empleados.groupby(["Genero",'Equipo'])["Salario"].aggregate(['mean', 'median'])

                                      mean    median
Genero Equipo
Hombre Desarrollo de Negocio  87851.000000   86615.0
       Desconocido            84061.208333   70443.0
       Distribución           92302.379310   91124.0
       Finanzas               95663.842105   91124.0
       Ingeniería             99937.027778  104794.5
       Legal                  84491.882353   77339.5
       Marketing              84406.432432   81919.0
       Producto               87615.435897   90429.0
       Recursos Humanos       92149.976744   96111.0
       Servicio al Cliente    93781.789474   98171.5
       Ventas                 93303.783784   91133.0
Mujer  Desarrollo de Negocio  92645.020408  104058.0
       Desconocido            82245.285714   78883.0
       Distribución           79812.161290   79796.0
       Finanzas               93483.333333   88980.5
       Ingeniería             89708.139535   89434.0
       Legal                  91749.242424   88276.0
       Marketing              97121.729730   97566.0
       Producto               86333.704545   87299.0
       Recursos Humanos       89835.878788   91411.0
       Servicio al Cliente    85742.723404   85718.0
       Ventas                 90055.628571   90582.0



---